select * from customer limit 5;


--what is the total revenue generated by male vs female customers..??
select gender, sum(purchase_amount) as revenue
from customer
group by gender ;
--which customer used discount but still spent more than average purchase amount
SELECT customer_id , purchase_amount
FROM customer c
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)

--which are the top 5 products with highest average review rating
WITH cte AS (
    SELECT 
        category,
        item_purchased,
        AVG(review_rating) AS average_rating,
        DENSE_RANK() OVER (
            PARTITION BY category 
            ORDER BY AVG(review_rating) DESC
        ) AS rank_in_category
    FROM customer
    GROUP BY category, item_purchased
)
SELECT *
FROM cte
WHERE rank_in_category <= 5;
;

--else for overall tts jst that
select item_purchased,category,round(avg(review_rating::numeric),2) as rating
from customer
group by item_purchased,category
order by avg(review_rating)desc
limit 5;

--compare the average purchase amount between standadrd and express shipping
select shipping_type,avg(purchase_amount) as average_amount
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type ;

-- do subscribed customers spend more.??compare average spend and total revenue between subcribers and non-subcribers
SELECT 
    subscription_status,                     -- yes / no
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue,
    COUNT(*) AS total_orders
FROM customer
GROUP BY  subscription_status ;

--which products have the highest percentage of purchases with discount applied
SELECT 
    item_purchased,
    SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

--top 5 items with the highest number of discounted purchases,
select item_purchased , count(*) as orders
from customer
where discount_applied ='Yes'
group by item_purchased
order by count(*)desc
limit 5;


--segment customers into new,loyal,returning based on there total number of previous purchases
--and show the count of each segment

WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

--which are the top 3 products purchased within each category

WITH product_totals AS (
    SELECT 
        category,
        item_purchased,
        SUM(purchase_amount) AS total_amount
    FROM customer
    GROUP BY category, item_purchased
),
ranked AS (
    SELECT
        category,
        item_purchased,
        total_amount,
        DENSE_RANK() OVER (
            PARTITION BY category ORDER BY total_amount DESC
        ) AS ranking
    FROM product_totals
)
SELECT category, item_purchased, ranking
FROM ranked
WHERE ranking <= 3;

-- are customers who are repeat buyers(more tahn 5 purchases) also likely to subscribe..?/

select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>=5
group by subscription_status 


--Best for understanding overall trend: does buying more lead to higher subscription?
select 
    previous_purchases,
    count(customer_id) as total_customers,
    sum(case when subscription_status='Yes' then 1 else 0 end) as subscribed
from customer
group by previous_purchases;

-- what is the revenue contribution for each age group

select age_group,
sum(purchase_amount) as revenue
from customer
group by age_group
order by sum(purchase_amount)desc;

